### ISSUE TITLE
Menubar looks funky on fullscreen

### ISSUE THREAD

**Issue by goldmahn** [jordanbaird/Ice#153] opened 2024-06-14 05:41 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Ever since updating to the current version (0.9.0), fullscreen looks odd.  See pictures for examples:
<img width="1470" alt="Fullscreen 1" src="https://github.com/jordanbaird/Ice/assets/14301865/9acecd51-0868-4bb7-924f-5283898509b3">
<img width="1470" alt="Fullscreen 2" src="https://github.com/jordanbaird/Ice/assets/14301865/2a6c1856-783d-41c0-9598-910890ce5e66">
<img width="1470" alt="Normal Screen 1" src="https://github.com/jordanbaird/Ice/assets/14301865/bd403fcc-7c3c-4552-b9db-f19178d503d0">
<img width="1470" alt="Normal Screen 2" src="https://github.com/jordanbaird/Ice/assets/14301865/adb1308f-b706-40d1-93a3-5562067394f5">

### Steps to Reproduce

1. Update to 0.9.0
2. Run app(s) on fullscreen
3. Be confused and annoyed

### Ice Version

0.9.0

### macOS Version

14.5 (23F79)

### Screenshots

<img width="1470" alt="Fullscreen 1" src="https://github.com/jordanbaird/Ice/assets/14301865/ada94429-9df9-459c-91ad-d23592b876a7">
<img width="1470" alt="Fullscreen 2" src="https://github.com/jordanbaird/Ice/assets/14301865/584f5e57-6e92-47d7-a791-22f13ad35aed">
<img width="1470" alt="Normal Screen 1" src="https://github.com/jordanbaird/Ice/assets/14301865/b43fec9e-94cb-40cd-bdfd-02e016c71dc3">
<img width="1470" alt="Normal Screen 2" src="https://github.com/jordanbaird/Ice/assets/14301865/af115198-ed36-4ab4-885d-6824848a65f7">

**Comment by goldmahn** [comment] 2024-06-14 05:56
Apologies - appears to be similar to #140.  Please feel free to merge or delete this.

**Comment by jvdbiam** [comment] 2024-06-14 06:28
Did you try changing color profiles in system preferences ? it worked for me.
I changed to a random one and then changed back to the default one.

**Comment by jordanbaird** [comment] 2024-06-16 03:32
Duplicate of #140

**Closed by jordanbaird** 2024-06-16 03:32 UTC
Labels: bug
