### ISSUE TITLE
[Feature Request]: A way to make the menu bar on non-notched macs look like the taller one on notched macs

### ISSUE THREAD

**Issue by FormalSnake** [jordanbaird/Ice#396] opened 2024-10-08 17:45 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

On notched macbooks, the menu bar has more padding and it just looks nicer and more modern. Currently, there is no way to get it on older macbooks seemingly and it would be cool if Ice could have it

### Screenshots

![image](https://github.com/user-attachments/assets/497aa15b-f703-4f2a-aa45-099817eb777a)

**Comment by jordanbaird** [comment] 2024-10-08 18:10
Duplicate of #264

**Closed by jordanbaird** 2024-10-08 18:10 UTC
Labels: Feature

**Comment by FormalSnake** [comment] 2024-10-08 19:26
whoops sorry

**Comment by jordanbaird** [comment] 2024-10-08 19:39
No worries.
