### ISSUE TITLE
[Bug]: Hidden menu items covered by MacBook Pro notch

### ISSUE THREAD

**Issue by colintclai** [jordanbaird/Ice#158] opened 2024-06-16 08:14 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I'm using a MacBook Pro 14" M1 Pro. As mentioned in the title, the hidden menu items are covered by the notch so they become inaccessible. There is no problem when I am using my 27" monitor when there is ample space to show everything.

### Steps to Reproduce

1. Use a MacBook Air / Pro
2. click on Ice icon
3. the menu bar extends to the notch and then nothing else

### Ice Version

0.9.0

### macOS Version

14.5 (23F79)

**Comment by jordanbaird** [comment] 2024-06-16 09:33
Duplicate of #1

**Closed by jordanbaird** 2024-06-16 09:33 UTC
Labels: bug
