### ISSUE TITLE
[Feature Request]: Hide current icons when more button is pressed

### ISSUE THREAD

**Issue by ImNoahDev** [jordanbaird/Ice#134] opened 2024-06-10 11:52 UTC
### Description

Hi,
I was wondering if it is possible to implement the bartender like behaviour where when a group is opened and there is not enough bar room, the items that are always on display get hidden until the bar is closed. 
This would make it easier to manage having icons on a small screen or a screen with a notch.

**Comment by jordanbaird** [comment] 2024-06-10 23:59
Duplicate of #68

**Closed by jordanbaird** 2024-06-10 23:59 UTC
Labels: enhancement
