### ISSUE TITLE
[Feature Request] Menu bar items search bar

### ISSUE THREAD

**Issue by Romachamp** [jordanbaird/Ice#265] opened 2024-07-23 13:03 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Hello! I would like to see menu bar items searching functionality, so I can search icons and open their windows, maybe, even with keyboard shortcuts like in Bartender.

**Comment by jordanbaird** [comment] 2024-07-23 14:12
Duplicate of #5

**Closed by jordanbaird** 2024-07-23 14:12 UTC
Labels: Feature
