### ISSUE TITLE
[Bug]: Can't remember position of 1Password menubar item

### ISSUE THREAD

**Issue by colintclai** [jordanbaird/Ice#374] opened 2024-09-24 06:00 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I'm using 1Password and have activated the 1Password menubar to the 'Visible Section'. But Ice always relocates it to the Always Hidden Section after every login or reboot. It has been like this from Mac OS 17 until now (18.1 beta 5).

### Steps to Reproduce

1. drag 1Password from Always hidden to Visible
2. restart or logout+login
3. 1Password icon goes back to Alway Hidden

### Ice Version

0.11.3

### macOS Version

18.1 beta 5

**Comment by jordanbaird** [comment] 2024-09-24 16:03
Duplicate of #344

**Closed by jordanbaird** 2024-09-24 16:03 UTC
Labels: Bug
