### ISSUE TITLE
[Bug]: <bug title>Menubar NOT the same on all 4 screens

### ISSUE THREAD

**Issue by polamco** [jordanbaird/Ice#360] opened 2024-09-20 03:40 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

i have 4 monitors,  1-16"MBP M1 Max, 1-49" widescreen,  and 2-16" panels, 
on 1 of my 16" panels , the menubar has more "empty space" at the start, leftmost position

see attached picture,     i would love for all 4 screens to show exactly the same!
<img width="576" alt="ICE SPACING BUG" src="https://github.com/user-attachments/assets/5aa71fc3-31e0-4c65-a4b1-efb3725258b6">

### Steps to Reproduce

just use a few monitors and see

### Ice Version

0.11.3

### macOS Version

14.4.1

### Screenshots

<img width="576" alt="ICE SPACING BUG" src="https://github.com/user-attachments/assets/89bc1321-f34c-4212-8188-225c06e7e573">

**Comment by jordanbaird** [comment] 2024-09-20 05:08
Duplicate of #359

**Closed by jordanbaird** 2024-09-20 05:08 UTC
Labels: Bug

**Comment by polamco** [comment] 2024-09-20 05:29
It's a similar issue, but not the same,   on all 4 screens,   i do have the split,      unlike #359 which one had split, and the other did not,   
it's just that one of my screens has that extra space,   
perhaps , it's the same "fix" for both ??    thanks for an awesome program!!

**Comment by jordanbaird** [comment] 2024-09-20 05:36
@polamco To fix that issue means addressing the extra space. Since it was opened first, I'm going to track the fix there.

**Comment by musiklee** [comment] 2024-09-20 05:53
thank you, looking forward to the fix
 i will have suggestions, to improve your app, if that's ok.  :-)

**Comment by jordanbaird** [comment] 2024-09-20 09:54
I'm always open to suggestions, and will do my best to implement them so long as they're possible and align with my vision for the app.
