### ISSUE TITLE
[Bug]: MacOS 15 Privacy Popups

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#170] opened 2024-06-20 16:39 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

So since macos 15 I get this popup each time Ice records something on my screen. If I click Continue, it popups again.
This is very annoying, anything that could be done to keep it to a minimum?

### Steps to Reproduce

1. Install MacOS 15
2. Run Ice

### Ice Version

0.10.0-beta.4

### macOS Version

15.0

### Screenshots

![image](https://github.com/jordanbaird/Ice/assets/32957125/2f75538e-cd03-4013-b872-1b00cbfc049f)

**Comment by lume96** [comment] 2024-06-20 17:10
Hi,
experiencing the same issue here (apart message being in French, not German ;-) ) on the same setup (MacOS 15 beta 1 and Ice 0.10 Beta 4)

However 2 points :

1. on my laptop this mainly only pops up once at the beginning of a session. Once I choose "continue to allow" I'm okay for the rest of the session
2. to answer to Jordans comment in the other thread : I do have other apps that are allowed to record screen and audio, such as CleanShotX and BTT that have never, up to now, seen this pop up regarding those other apps.

**Comment by jordanbaird** [comment] 2024-06-20 20:18
Does anyone have an English version of the alert? Preferably not a translation, but the actual English alert that shows up, so I can Google it :)

**Comment by Xytronix** [comment] 2024-06-21 06:11
Here is it:

<img width="328" alt="image" src="https://github.com/jordanbaird/Ice/assets/32957125/fa777165-d2e7-46dd-8145-8b95791cfd35">
It stopped reappearing after clicking continue since a reboot. It appears every time Ice is launched after a reboot.

**Comment by Xytronix** [comment] 2024-06-24 07:24
Did occur again after being in standby for a while even when Ice was closed

**Comment by jordanbaird** [comment] 2024-06-25 12:09
I think this is most likely a bug with the macOS 15 beta. In fact, it seems like I remember reading something similar happening in some of the early macOS 14 betas that was resolved before its official release.

**Comment by WardsParadox** [comment] 2024-06-28 16:02
This is not due to a bug in macOS 15, this is due to the following per Apple's documentation and enterprise support recommendations:

>Applications utilizing deprecated APIs for content capture such as CGDisplayStream & CGWindowListCreateImage can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to ScreenCaptureKit and SCContentSharingPicker. (120910350)

https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#Deprecations

This was announced in 2022 with Sonoma beta, and the experience was so poor Apple removed the notifications in favor of the next OS (now 15, Sequoia)

**Comment by WardsParadox** [comment] 2024-06-28 16:03
Looks like it's this line:
https://github.com/jordanbaird/Ice/blob/79a833ee963b0d99a2798dbe10bd782f263569c8/Ice/Bridging/Bridging.swift#L221

**Comment by Xytronix** [comment] 2024-06-28 17:25
> This is not due to a bug in macOS 15, this is due to the following per Apple's documentation and enterprise support recommendations:
> 
> > Applications utilizing deprecated APIs for content capture such as CGDisplayStream & CGWindowListCreateImage can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to ScreenCaptureKit and SCContentSharingPicker. (120910350)
> 
> https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#Deprecations
> ``

**Comment by Xytronix** [comment] 2024-06-28 17:25
Sorry for closinh

**Comment by jordanbaird** [comment] 2024-06-28 17:28
@WardsParadox We don't have the option to use ScreenCaptureKit. It can't capture of offscreen items. Until Apple adds support for that, this is quite literally our only option.

**Comment by WardsParadox** [comment] 2024-06-28 17:31
I'll let our support know this and see what they suggest. ☝🏻This☝🏻may be enough for us to push this further back. It also shouldn't be prompting more than once like it is now which is feedback we're already sending in. 

Thanks for the further info.

**Comment by jordanbaird** [comment] 2024-06-28 17:45
It's this line that lets us do the offscreen capture:

https://github.com/jordanbaird/Ice/blob/79a833ee963b0d99a2798dbe10bd782f263569c8/Ice/Bridging/Bridging.swift#L213

Which is the Swift overlay for `CGWindowListCreateImageFromArray`, so the same family of functions. In the meantime, I can migrate the line you linked above to use `SCScreenshotManager`.

**Comment by jordanbaird** [comment] 2024-07-24 03:38
@WardsParadox Any update on this?

**Comment by WardsParadox** [comment] 2024-07-29 17:33
So far the response is "Developers need to move onto newer APIs" so we're starting the "and if those API's don't exist" talks. :(

**Comment by WardsParadox** [comment] 2024-07-31 18:33
We've put additional pressure through our enterprise channel, so 🤞🏻 for some additional info soon.

**Comment by stonerl** [comment] 2024-08-02 09:15
Just to add my 2 cents. I know most of it has been said, but here it is asummary .

This is from macOS 15 Beta 4 Release Notes:

> **ScreenCaptureKit**
> 
> _New Features_
> 
> - Windows recorded using the new SCRecordingOutputConfiguration API will now have a new "Stop Recording This Window" menu item in the purple window menu to stop the window's recording stream. (125112908)
> 
> 
> _Deprecations_
> 
> - Applications utilizing deprecated APIs for content capture such as **CGDisplayStream & CGWindowListCreateImage** can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to **ScreenCaptureKit** and **SCContentSharingPicker**. (120910350)


Also in XCode I get deprication messages for the following lines:

https://github.com/jordanbaird/Ice/blob/2332b0159adf1b4398f3bd56ebd800b2d07383e9/Ice/Bridging/Bridging.swift#L213

> 'init(windowListFromArrayScreenBounds:windowArray:imageOption:)' was deprecated in macOS 14.0: Please use ScreenCaptureKit instead.

https://github.com/jordanbaird/Ice/blob/2332b0159adf1b4398f3bd56ebd800b2d07383e9/Ice/Bridging/Bridging.swift#L221

> 'CGWindowListCreateImage' was deprecated in macOS 14.0: Please use ScreenCaptureKit instead.

**Comment by jordanbaird** [comment] 2024-08-02 13:04
@WardsParadox Would it help if I opened my own ticket with Apple? Maybe additional feedback would help them see that this is indeed a problem.

**Comment by stonerl** [comment] 2024-08-06 11:22
The popup has changed with macOS 15 beta 5.

![CleanShot 2024-08-06 at 13 20 54@2x](https://github.com/user-attachments/assets/b3fe4274-77a0-4925-912b-b3941b0b36f1)

**Comment by WardsParadox** [comment] 2024-08-06 17:26
>@WardsParadox Would it help if I opened my own ticket with Apple? Maybe additional feedback would help them see that this is indeed a problem.

It looks like my previous comment never posted. Yes please! If you can link the ID of the case, I'll reference it on ours as an impacted app due to missing APIs

**Comment by terafin** [comment] 2024-08-08 04:04
https://developer.apple.com/documentation/screencapturekit/scshareablecontent/3916730-getshareablecontentexcludingdesk?language=objc

**Comment by jordanbaird** [comment] 2024-08-08 04:35
@terafin The problem isn't getting the windows. The problem is capturing an image from them. It's been a while since I messed with it, but if I'm remembering correctly, it either throws an error, hangs, or returns a blank image.

**Comment by jordanbaird** [comment] 2024-08-08 04:46
@stonerl Yikes. This is even worse than before. People are going to panic when they see that. I want to make it clear that Ice does NOT record private aspects of the screen and never will.

Here are the things it captures:

1. The desktop wallpaper image, so it can display it over the top of the menu bar when using the various menu bar shape options. It doesn't capture desktop icons, or widgets. Just the wallpaper.
2. Individual menu bar items, so it can display them in settings and the Ice Bar.

**Comment by terafin** [comment] 2024-08-08 05:02
> @terafin The problem isn't getting the windows. The problem is capturing an image from them. It's been a while since I messed with it, but if I'm remembering correctly, it either throws an error, hangs, or returns a blank image.

Might be worth trying again, worked for me :)

**Comment by jordanbaird** [comment] 2024-08-08 05:20
@terafin Even for offscreen menu bar items? Maybe they fixed it. Which version of macOS?

**Comment by terafin** [comment] 2024-08-08 05:31
> @terafin Even for offscreen menu bar items? Maybe they fixed it. Which version of macOS?

Didn't try that, but 14.5, worth a shot?

**Comment by jordanbaird** [comment] 2024-08-08 05:41
@terafin I guess it's worth another shot, but onscreen items have never been the problem. It's only ever been offscreen, so I doubt anything has changed. I'll still check though.

**Comment by terafin** [comment] 2024-08-08 05:54
> @terafin I guess it's worth another shot, but onscreen items have never been the problem. It's only ever been offscreen, so I doubt anything has changed. I'll still check though.

@jordanbaird Awesome, thanks! I suspect if it doesn't work, that might be a more concise and clear bug report since I think that's the "intended" API :) Who knows, maybe it's a more specific bug that can be fixed!

**Comment by stonerl** [comment] 2024-08-15 09:39
According to 9to5mac it now only asks once a month [](https://9to5mac.com/2024/08/14/macos-sequoia-screen-recording-prompt-monthly/)

**Comment by jordanbaird** [comment] 2024-08-15 12:44
@stonerl That's better than it was at least, but I agree with their opinion that it's still over the top. In my opinion, it should be an opt-in feature, or at least let users opt out for individual apps. The wording of the alert is improving as well. I'm still going to submit feedback to Apple about the missing functionality in ScreenCaptureKit, since I really do want to migrate to the newer APIs. But this at least makes it a little less pressing.

**Comment by luckman212** [comment] 2024-08-15 12:53
Looks like macOS 15 is truly going to be Apple's [Vista][1]...

[1]: https://arstechnica.com/information-technology/2008/04/vistas-uac-security-prompt-was-designed-to-annoy-you/

**Comment by kocane** [comment] 2024-09-04 12:00
Why do they have to treat us like we're retarded? Let us "allow always", god damn it.

**Comment by jordanbaird** [comment] 2024-09-04 13:05
@kocane While I do agree with your sentiment, please follow our code of conduct by keeping that kind of language outside of this repository. Thanks.

**Comment by jordanbaird** [comment] 2024-09-16 13:25
I'm going to close this, as Sequoia is releasing today, and Apple seems to have settled on the once-a-month popup. There isn't much Ice can do about this, aside from implementing the new ScreenCaptureKit APIs (which we can't do for the reasons described above).

**Closed by jordanbaird** 2024-09-16 13:25 UTC
Labels: Bug, Screen Capture

**Comment by luckman212** [comment] 2024-09-16 13:28
Thank you @jordanbaird 

Hopefully there will be enough outrage from this annoying change that Apple will reconsider this for 15.1

**Comment by stonerl** [comment] 2024-09-23 17:07
This little app here might be what we are looking for: [Amnesia](https://goodsnooze.gumroad.com/l/amnesia)

**Comment by stonerl** [comment] 2024-10-09 13:14
>ScreenCaptureKit
>
>New Features
>
>Applications using our deprecated content capture technologies now have enhanced user awareness policies. Users will see fewer dialogs if they regularly use apps in which they have already acknowledged and accepted the risks. (133431080)

New changes in macOS 15.1 beta6. Not sure what this means in practice, but let's hope for less popups.
