### ISSUE TITLE
[Feature Request]: Allow limit features in the app without screen sharing permission

### ISSUE THREAD

**Issue by dslittle22** [jordanbaird/Ice#270] opened 2024-07-26 02:18 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

I want to use this app on my work computer, but can't because it requires screen recording permission. I think it'd be great if we could run some features of the app without screen recording permission, like most things except for changing menu bar appearance.

**Comment by jordanbaird** [comment] 2024-07-26 11:05
Duplicate of #75

**Closed by jordanbaird** 2024-07-26 11:05 UTC
Labels: Feature
