### ISSUE TITLE
[Feature Request]: Arrange "Hidden" and "Always Hidden" Section Items w/ cmd+drag

### ISSUE THREAD

**Issue by musiklee** [jordanbaird/Ice#365] opened 2024-09-20 16:50 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

i searched but didn't find,  sorry if request already exists...

i basically want to arrange the "Hidden" and "Always Hidden" as we can the "Visible Section"  with cmd+drag
without having to go into Settings, Menu Bar Layout

**Comment by jordanbaird** [comment] 2024-09-20 17:00
Are you using the Ice Bar? If you turn that off, you can do this, but the change should definitely be made to allow this regardles of whether you have the Ice Bar enabled. Are you wanting the items to be arrangeable inside the Ice Bar?

**Comment by musiklee** [comment] 2024-09-20 17:08
you are a mind reader, and i was just abou tto edit my post
 
YES,   in the Ice Bar below,  and Always Hidden bar below that
     
i saw you can drag the hidden when not using Ice Bar, (when all on top row),   ;-)

if you could add that feature ,  would be AMAZING!!!

**Comment by musiklee** [comment] 2024-09-20 17:10
could i be the 1st to ask for this?     
seems useful, and necessary for those that like using Ice Bar, those with MBP w/Notch
hopefully it can be implemented.   THANK YOU!!!!

**Comment by jordanbaird** [comment] 2024-09-20 17:15
This is actually already a feature request, so I'll close this. It's been in my backlog for a while, as there are more pressing bugs to fix and features to implement, but I'll try to get it done relatively soon.

**Comment by jordanbaird** [comment] 2024-09-20 17:15
Duplicate of #209

**Closed by jordanbaird** 2024-09-20 17:15 UTC
Labels: Feature
