### ISSUE TITLE
[Bug]: Dato menu loads in far left corner instead of being anchored to icon in far right corner

### ISSUE THREAD

**Issue by autonome** [jordanbaird/Ice#169] opened 2024-06-19 15:31 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

The menu loads on the far left, but should load on the far right.

### Steps to Reproduce

1. Install Dato: https://sindresorhus.com/dato
2. Open the Dato menu

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

![CleanShot 2024-06-19 at 17 31 14@2x](https://github.com/jordanbaird/Ice/assets/50103/843f1d37-05b5-4879-9fb5-655596f2c6d9)

**Comment by luckman212** [comment] 2024-06-21 15:28
I have this too. Same OS, same app (although I am using the Setapp version)

**Comment by luckman212** [comment] 2024-06-24 15:25
Running 0.10b5 now, and still having the issue where "new" icons (not really new, just re-appearing ones that I've moved out from the "always-hidden" section before) are being placed at the end of the line and thus not visible when I need them to be.

It also affects menubar icons that are added by Hammerspoon, of which I have several that appear and disappear depending on various things happening on my Mac.

I was wondering if there was a hidden setting to control this behavior somewhere that I'm not seeing in the UI?

I see that some of the other related issues around this are now closed, so I'm hopeful there are still some more changes coming... probably https://github.com/jordanbaird/Ice/issues/6 is the correct one to follow?

I'll link these here just for reference:

- [🛣️ 0.11.0 Milestone](https://github.com/jordanbaird/Ice/milestone/2)
- https://github.com/jordanbaird/Ice/issues/119
- https://github.com/jordanbaird/Ice/issues/164
- https://github.com/jordanbaird/Ice/issues/172

**Comment by jordanbaird** [comment] 2024-06-24 16:14
#6 would be the correct one to follow, yes. That and #26, which will enable Ice to remember the locations of existing items.

**Comment by luckman212** [comment] 2024-07-03 14:20
Is this problem unique to [Dato.app](https://sindresorhus.com/dato)? I have other menubar items e.g. [DatWeatherDoe](https://github.com/inderdhir/DatWeatherDoe) whose text also changes periodically, yet their position remains correct. For some reason, Dato constantly "jumps" to the back of the line. Is there a reason to ask @sindresorhus if he's doing something unorthodox that would cause this behavior?

**Comment by jordanbaird** [comment] 2024-07-03 14:30
@luckman212 Does Dato dynamically create its item(s) during runtime? As in, it might add and remove them while it's still running? If so, I think it's following the default behavior, which deletes the item's stored position when the it is removed. I had to manually work around it with Ice by caching the position before removing the item and storing it again afterward.

**Comment by luckman212** [comment] 2024-07-03 15:52
Yes, it definitely adds/removes elements during its lifetime. It displays upcoming calendar events so is constantly changing. It's not open source so I am not sure what methods are being used, but I will say, when Ice is not running, Dato's menubar position stays intact.

**Comment by luckman212** [comment] 2024-07-09 12:35
I just installed 0.10.1 and after the dialog appeared telling me it had to trash my prefs due to corruption, it seems the Dato menuitem is staying where I put it now! 👍  I didn't see this mentioned in the release notes anywhere but—has something changed here that might have caused this to be fixed? Or was it the recreation of the prefs you think?

Strangely, now my "WiFi" icon seems to be suffering from the same problem- it keeps disappearing and getting moved to the hidden section, even after dragging it back.

**Comment by jordanbaird** [comment] 2024-07-09 12:48
@luckman212 Hmm...I can't think of any reason why it would be working now when it wasn't before. Strange that your WiFi icon is doing this. Is it the standard macOS WiFi icon, or do you use a third party app?

**Comment by luckman212** [comment] 2024-07-09 13:21
Just the standard WiFi icon. I quit Ice and relaunched it, and so far it's working again. Maybe a fluke. Where does Ice store its preferences for the icon ordering? (just in case I want to manually trash it again) I glanced over the source but couldn't spot it.

**Comment by luckman212** [comment] 2024-07-09 13:33
For anyone having this problem, I found a temporary workaround inside Dato itself:

If you go to Dato's Settings → Events and click **Customize**, and then scroll all the way down, there is a toggle called _Show menu bar item even when there are no upcoming events_:

<img src=https://github.com/jordanbaird/Ice/assets/1992842/c3ab64d3-bee3-4973-ae31-957fb9dad0ed width=400> <br>

<img src=https://github.com/jordanbaird/Ice/assets/1992842/384185a7-4b54-400d-89eb-b655235b751d width=400>

If enabled, a small "diamond" appears as a placeholder. This seems to allow Ice and/or macOS to preserve the menuitem ordering for the Dato meeting reminders.

<img width="244" src="https://github.com/jordanbaird/Ice/assets/1992842/35105dda-5bc4-4e6f-b924-8e6dd2bc07bc">

**Comment by autonome** [comment] 2024-08-28 11:54
FYI the problem originally reported in this issue no longer seems to occur in latest Ice.

**Comment by luckman212** [comment] 2024-08-28 13:21
@autonome Was it an Ice update or a Dato update (or both) that fixed the issue?

**Comment by autonome** [comment] 2024-08-28 13:26
Good question, I don't know! I had updated Ice recently, so I assumed it was that. However, I didn't roll back and test.

**Comment by luckman212** [comment] 2024-08-28 13:49
I just tested it, still broken for me: Ice 0.11.0-beta1, Dato v5.3.6 Setapp.

If I don't use the [workaround above][1] then new calendar reminders are inserted at the far left, hidden in the Ice bar... so I never see them.

[1]: https://github.com/jordanbaird/Ice/issues/169#issuecomment-2217761235

**Comment by autonome** [comment] 2024-08-28 14:11
I'm specifically talking about the issue that I reported in the first comment here - the menu loading on the right.

I'm seeing that Dato's meeting reminders are continually moved to the Always-Hidden section even though I move them back. But that's different entirely, and should be a separate issue probably.

**Comment by luckman212** [comment] 2024-08-29 15:07
@autonome I believe instead of opening a new issue, https://github.com/jordanbaird/Ice/issues/119 should just be re-opened. I understand that we are waiting for the 0.12.x milestone for this, but IMO that issue should still be marked Open, if not at least to avoid people re-posting the same problem.

**Comment by jordanbaird** [comment] 2024-10-08 15:37
Seems I lost track of this issue. I'm confident that this was a bug with Dato. Ice doesn't do anything to change where an item's menu appears. Regardless, as it seems to be fixed now, I'm going to close this.

**Closed by jordanbaird** 2024-10-08 15:37 UTC
Labels: Bug

**Comment by luckman212** [comment] 2024-10-08 23:05
@jordanbaird Sorry to throw cold water on this, but...

> _"I'm confident that this was a bug with Dato."_ 

Any chance you could reach out to @sindresorhus about that, because it's an awfully popular app, and seems a shame that it appears to have this incompatibility with arguably the best menubar-taming app on macOS these days. I've messaged him about it, but as the developer of the app I'm sure your message would carry more weight.

> _"as it seems to be fixed now, I'm going to close this."_

I can't find any evidence that this is fixed. I'm using macOS 15.0.1 (also tried 15.1b6) with Ice 0.11.9 + Dato 5.3.7, and I can't get this to behave properly at all unless I enable Dato's "diamond item workaround" [mentioned a little further up](https://github.com/jordanbaird/Ice/issues/169#issuecomment-2217761235) in this thread.

The symptom is: upcoming reminders completely disappear. They are not visible in the menu bar, or in Ice's hidden sections either. They also do not appear in the Ice settings dialog under Menu Bar Layout. They're simply invisible until I quit Ice completely, at which point they appear.

**Comment by jordanbaird** [comment] 2024-10-08 23:36
@luckman212 This issue is specifically for Dato's menu appearing at the far left of the screen, and is not related to the issue with its menu bar item appearing in the always-hidden section. That issue is due to the lack of profiles, and is tracked as a feature request in #26. Unfortnuately, I still haven't had time to implement it, as I've been focusing on fixing _lots_ of other bugs, especially usability issues that have popped up since the Sequoia release.

I'm going off of what @autonome said [here](https://github.com/jordanbaird/Ice/issues/169#issuecomment-2315121422) as evidence that this is fixed.

As for the behavior your referring to, this would not be a bug with Dato, nor is it a bug with Ice. It's simply due to the way macOS treats new menu bar items. Ice just doesn't have a feature to compensate for this, which is why #26 is a feature request and not a bug report (see #298 for more details). Regardless, I don't think there's anything for Sindre to do on his end, as Dato needs to be able to create new menu bar items on the fly. It's on Ice to keep track of them.

**Comment by luckman212** [comment] 2024-10-09 00:29
Thanks for that, ok I'll stop asking about this one. Sounds like it's on your radar and we just need to have patience and a bit of faith.

**Comment by jordanbaird** [comment] 2024-10-09 13:41
@luckman212 No worries. I'm hoping to get started on it soon, barring any unforseen circumstances.
