### ISSUE TITLE
[Feature Request]: Preference for which section to place new menu bar items into

### ISSUE THREAD

**Issue by niclake** [jordanbaird/Ice#357] opened 2024-09-17 20:08 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Would love to have a preference allowing us to choose which of the sections (Visible, Hidden, Always Hidden) new menu bar items go into. By default, it dumps into Always Hidden, which feels wrong to me; sending it to either Visible (and letting me update) or Hidden (and inviting me to either surface or banish it - this is my personal preference).

**Comment by jordanbaird** [comment] 2024-09-17 22:27
Duplicate of #6

**Closed by jordanbaird** 2024-09-17 22:27 UTC
Labels: Feature
