### ISSUE TITLE
[Feature Request]: pause functionality when connected to big screen

### ISSUE THREAD

**Issue by dkocich** [jordanbaird/Ice#465] opened 2024-12-20 07:47 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

- allow to make it work only on one screen - MacBook with notch; otherwise on the second screen it will display classic icons all over the panel (21 to 9 screen with plenty of space)
- possibly set the option to pause ice when some external device is detected (USB-C dock withthe  monitor plugged in or other) so it stops working on my dock and starts working when I go away for a meeting

**Comment by mnemnion** [comment] 2024-12-22 20:03
This is roughly what brought me to the issue board today.  Great app!

"Expand everything when a monitor is plugged in" would be plenty, what I had in mind was per-display configurations.  I have a few icons, like the Stream Deck one, which only matter when I'm using a monitor, but there are still a few that I'd rather have hidden when plugged in.  I don't think that's different enough from this one to be its own feature request though.

**Comment by mnemnion** [comment] 2024-12-22 20:14
This is arguably a duplicate of #223 though.

**Comment by jordanbaird** [comment] 2024-12-28 13:19
This is really a multi-part feature, and is covered by #223, #299, and #303.

**Closed by jordanbaird** 2024-12-28 13:19 UTC
Labels: Feature
