### ISSUE TITLE
[Bug]: I run the app CleanShotX and at least once a day Ice moves the icon from hidden to visible

### ISSUE THREAD

**Issue by geigel** [jordanbaird/Ice#419] opened 2024-10-28 17:38 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I run the app CleanShot X (CSX) which is a popular screen capture app (https://cleanshot.com/) and I have it in my "Hidden" menu bar within Ice. As I use CSX throughout the day at some point it always moves itself to the "visible" part of my menu bar. Or, if I close CSX and then reopen it, it moves it there too. So I'm always going back to Ice settings to again move it back to the hidden area. It seems to be the only app I have an issue with.

### Steps to Reproduce

No truly identifiable way to reproduce it. I just happen to notice that the CSX app has at some point found itself in the visible part of my menu bar since it's a little wider. I'm using the CSX app to take screenshots of things so maybe that's bumping into Ice trying to do that at the same time? Figured I'd share it since it's really the only issue I've seen in Ice. 

### Ice Version

0.11.7

### macOS Version

15.1 (24B83)

**Comment by jordanbaird** [comment] 2024-10-28 19:00
I'm going to treat this as a duplicate of #344, as it's the same fundemental issue. Ice isn't moving it, either macOS is moving it, or it's moving itself.

**Closed by jordanbaird** 2024-10-28 19:00 UTC
Labels: Bug
