### ISSUE TITLE
[Feature Request]: Temporary show hidden icon on update (Bartender Triggers)

### ISSUE THREAD

**Issue by JensjJ8200** [jordanbaird/Ice#317] opened 2024-08-15 17:24 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hello I am switching from Bartender to Ice (due to the change of owner).
There was a bartender feature I really liked, and used a lot, but Is not in Ice.
The ability to have an app "unhide", if it updates – for a limited time. E.g. if my battery goes below 20%, then the battery icon becomes visible. etc.

### Screenshots

nine

**Comment by JensjJ8200** [comment] 2024-08-15 17:25
On the Bartender it's called Triggers.

**Comment by jordanbaird** [comment] 2024-08-15 19:33
Duplicate of #62

**Closed by jordanbaird** 2024-08-15 19:33 UTC
Labels: Feature
