### ISSUE TITLE
[Feature Request]: remove screen recording

### ISSUE THREAD

**Issue by deardaveed** [jordanbaird/Ice#415] opened 2024-10-23 19:18 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hi --- thank you for your hard work. Why is it apps like Bartender and Ice must require screen recording, but an app like Hidden Bar doesn't?

Can we remove screen recording? I understand this is open source, but I imagine it wouldn't be too difficult for nefarious actors to slip in some kind of code that sends screenshots back to an address?

**Comment by Write** [comment] 2024-10-23 21:12
Duplicate of https://github.com/jordanbaird/Ice/issues/75

**Comment by jordanbaird** [comment] 2024-10-23 23:21
As @Write said, this is a duplicate. There is a pull request open that I believe will address these changes, but I haven't had time to look at it yet.

**Closed by jordanbaird** 2024-10-23 23:21 UTC
Labels: Feature

**Comment by jordanbaird** [comment] 2024-10-23 23:23
As for the reasons why Ice requires screen recording permissions, see #362
