### ISSUE TITLE
[Feature Request]: Add Spacers in Menu Bar

### ISSUE THREAD

**Issue by MrMegira** [jordanbaird/Ice#366] opened 2024-09-20 23:01 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Option to Add Spacers to the Menu Bar for Better Layout Customization

### Screenshots

I’ve attached an example for illustration 

![CleanShot 2024-09-21 at 02 01 11@2x](https://github.com/user-attachments/assets/f52372d2-4702-4edf-9070-af7eada816f1)

**Comment by jordanbaird** [comment] 2024-09-20 23:44
Duplicate of #91

**Closed by jordanbaird** 2024-09-20 23:44 UTC
Labels: Feature

**Comment by jordanbaird** [comment] 2024-09-20 23:45
If you want the lines in the spacers, please comment on the existing issue. Do not open a new one.
