### ISSUE TITLE
The bar shows an error when I have multiple screens.

### ISSUE THREAD

**Issue by iFurySt** [jordanbaird/Ice#168] opened 2024-06-19 09:47 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

It shows fine in the main screen.
![Xnip2024-06-19_17-08-15](https://github.com/jordanbaird/Ice/assets/16201837/dfe8d8c4-ddab-4788-96cc-47c582b9ba0e)

But the height is mismatched.
<img width="1512" alt="Xnip2024-06-19_17-08-00" src="https://github.com/jordanbaird/Ice/assets/16201837/56133166-c384-4c9c-845b-2069136e1273">

### Steps to Reproduce

I don't know if this situation can be reproduced when using multi-screens.

### Ice Version

0.9.0

### macOS Version

Sonoma 14.5 (23F79)

**Comment by jordanbaird** [comment] 2024-06-19 10:02
Duplicate of #97

**Closed by jordanbaird** 2024-06-19 10:02 UTC
Labels: bug
