### ISSUE TITLE
[Bug]: Icon does not show up in menu bar

### ISSUE THREAD

**Issue by zoulhh** [jordanbaird/Ice#356] opened 2024-09-17 19:30 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I got an app called OpenVPN Connect. When started, it shows up in the menu bar. When Ice is running, it doesn't. It is not hidden, it is simply not there until I quit Ice.

### Steps to Reproduce

Launch OpenVPN Connect

### Ice Version

0.11.2

### macOS Version

macOS 15

**Comment by jordanbaird** [comment] 2024-09-17 22:26
It's almost definitely being moved into the always-hidden section. Duplicate of #344

**Closed by jordanbaird** 2024-09-17 22:26 UTC
Labels: Bug
