### ISSUE TITLE
[Feature Request]: Battery icon (or other items) hidden when charging

### ISSUE THREAD

**Issue by xx88xx** [jordanbaird/Ice#432] opened 2024-11-09 09:31 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Bartender had a feature where if the battery of your macbook was charging, you could hide it (as it's kinda useless information considering), but if the MacBook is unplugged (ie. running on battery) it would show up. 

Would we be able to implement this feature?

**Comment by jordanbaird** [comment] 2024-11-09 16:42
Duplicate of #62

**Closed by jordanbaird** 2024-11-09 16:42 UTC
Labels: Feature
