### ISSUE TITLE
[Bug]: already has been set to a hidden icon. When the program exits and starts again, the icon will return to "visible"

### ISSUE THREAD

**Issue by cevin** [jordanbaird/Ice#249] opened 2024-07-17 00:55 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

![Snipaste_2024-07-17_08-48-03](https://github.com/user-attachments/assets/f6ed86cd-1c4a-4203-b73a-8e229eb89bef)

Program: 

https://u.tools

https://open.u-tools.cn/download/uTools-5.1.1-arm64.dmg

I have set the project to "hidden". But when the program exits and starts again, its icon will appear in "visible" instead of "hidden".

### Steps to Reproduce

1. Set to Hide
2. Exit the program
3. Start it again

### Ice Version

0.10.2

### macOS Version

14.5

**Comment by allyson-c** [comment] 2024-07-17 22:45
I can reproduce this issue with the above program. Seems like it affects certain apps, including Cleanshot like in issue #244

**Comment by jordanbaird** [comment] 2024-07-18 00:17
@allyson-c I think you're right. I'll close this as a duplicate of #244.

**Closed by jordanbaird** 2024-07-18 00:17 UTC
Labels: Bug
