### ISSUE TITLE
[Bug]: Menu bar shapes didn't appear to work

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#47] opened 2024-04-10 09:50 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Shapes don't appear to work with the latest version. I do have tint and shadow activated so perhaps this has to do with it?
In addition menu bar items are out of range to be accessed ( too many icons in the menu bar)

### Steps to Reproduce

1. Go to menu bar
2. Assign shape

### Ice Version

0.8.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment] 2024-04-10 22:11
Could you post a screenshot of what it looks like? Even if it looks like nothing, it will still be helpful.

**Comment by uncenter** [comment] 2024-04-11 11:25
I thought I had a similar issue - restarted my computer to update (to 14.4.1) and after the update completed the menubar was no longer split as configured. I originally thought maybe the update somehow broke it, but it looks like closing and reopening Ice did the trick to get the shape to apply again. Hope that helps.

**Comment by TonioGela** [comment] 2024-06-06 13:45
I can confirm that on Sonoma 14.4.1 and Sonoma 14.5 with the `Automatically Hidden Menu Bar` Setting on, Shapes do not work as per the screenshot.
![image](https://github.com/jordanbaird/Ice/assets/41690956/c4067ba1-2c52-4f8d-9796-0c2f473def8f)

I also noticed that the `Hide application menus when showing menu bar items` setting is not honoured, so I wonder if it's due to a change in the MenuBar API.

I'll be glad to provide further help/info if necessary, feel free to ask

**Comment by jordanbaird** [comment] 2024-06-06 13:52
I just pushed out an update (0.9.0) a couple hours ago, could those in this thread that have this issue confirm whether it's still a problem after updating?

**Comment by jordanbaird** [comment] 2024-06-06 13:56
@TonioGela When you say `Automatically Hidden Menu Bar` settings, do you mean the setting in the Control Center pane of macOS System Settings?
<img width="827" alt="SCR-20240606-hmsc" src="https://github.com/jordanbaird/Ice/assets/90936861/3a37bedb-07ea-4fa1-8d5a-fa803cf709ec">

**Comment by TonioGela** [comment] 2024-06-06 14:13
> @TonioGela When you say `Automatically Hidden Menu Bar` settings, do you mean the setting in the Control Center pane of macOS System Settings?

The one in macos System Settings. Funnily enough, disabling and re-enabling it made the menubar styling work again 🤔

**Comment by jordanbaird** [comment] 2024-06-06 14:23
@TonioGela Okay, yeah. I can reproduce this. I didn't take the automatically hiding menu bar into account when I implemented the appearance features. I'll need to figure out some way to check if the menu bar is visible and hide/show the appearance overlay accordingly.

**Comment by TonioGela** [comment] 2024-06-06 14:25
> @TonioGela Okay, yeah. I can reproduce this. I didn't take the automatically hiding menu bar into account when I implemented the appearance features. I'll need to figure out some way to check if the menu bar is visible and hide/show the appearance overlay accordingly.

Ah okay, makes sense. You need to check whether there's an os-level API that exposes that setting.

In any case, it's not affecting my user experience as I'm not using this feature. So don't worry about me ;)

**Comment by TonioGela** [comment] 2024-06-06 14:32
And I think I found a way to programmatically tell it :D

```
defaults read NSGlobalDomain "_HIHideMenuBar"
```

**Comment by jordanbaird** [comment] 2024-06-06 14:48
My only concern there is the underscore, meaning it's a private API and could change in any macOS release. A reliable way (albeit more expensive) is to use the `CGWindowList` API to get a list of onscreen windows and filter out the one whose layer is `kCGMainMenuWindowLevel`. But I worry that might be too computationally expensive, as we'd have to do it repeatedly. I think I'm going to look into the `Accessibility` API to see if there's a way I can observe the menu bar window frame, but I may use the `defaults` method as a backup.

**Closed** 2024-06-21 05:52 UTC
Labels: bug
