### ISSUE TITLE
[Bug]: <ice cannot arrange menubar items in automatically hidden menu bars>

### ISSUE THREAD

**Issue by kdifnv** [jordanbaird/Ice#458] opened 2024-12-04 15:59 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

cant change layout

### Steps to Reproduce

1.open ice 
2.click menu bar layout

### Ice Version

0.11.12

### macOS Version

sequoia 15.0

### Screenshots

<img width="1421" alt="Screenshot 2024-12-04 at 7 59 43 PM" src="https://github.com/user-attachments/assets/2e265324-e924-4014-9ac3-f0d654254b44">

**Comment by jordanbaird** [comment] 2024-12-28 13:34
Duplicate of #201

**Closed by jordanbaird** 2024-12-28 13:34 UTC
Labels: Bug
