### ISSUE TITLE
[Bug]: NextDNS menu item doesn't stick after restart

### ISSUE THREAD

**Issue by Mudflapper** [jordanbaird/Ice#448] opened 2024-11-27 15:42 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The Mac App Store NextDNS.app's menubar item doesn't stick where I put it in the Visible Section. On initial boot or upon restart it always moves to the Hidden Section. 

### Steps to Reproduce

1. Install NextDNS.app from Mac App Store
2. Put menubar icon in Visible Section
3. Restart
4. Icon moves to Hidden Section

### Ice Version

0.11.12 currently, but all versions I've used since installing NextDNS 3 months ago

### macOS Version

15.1 public through 15.2 beta (current)

### Screenshots

![Screen Shot 2024-11-27 at 9 35 50 AM](https://github.com/user-attachments/assets/1d6b1e80-9c94-4104-9371-694fd31a835f)
![Screen Shot 2024-11-27 at 9 34 53 AM](https://github.com/user-attachments/assets/47107613-4066-48be-9576-53ff8a26c088)

**Comment by jordanbaird** [comment] 2024-11-27 21:07
Duplicate of #344

**Closed by jordanbaird** 2024-11-27 21:07 UTC
Labels: Bug
