### ISSUE TITLE
[Feature Request]: <Newly installed apps should have their icon put into the "Always visible" group, not into "always hidden">

### ISSUE THREAD

**Issue by galgogergo** [jordanbaird/Ice#457] opened 2024-12-03 22:41 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

As the title says. I could barely figure out where my recently installed app (PasteKit) went, and why I couldn't find it in the menu bar, until I remembered there is an always hidden section configurable. 
But why does Ice put freshly installed apps instantly there instead of the always visible group? I'll move it from there if it bothers me.

**Comment by jordanbaird** [comment] 2024-12-04 01:54
Duplicate of #6

**Closed by jordanbaird** 2024-12-04 01:54 UTC
Labels: Feature
