### ISSUE TITLE
[Feature Request]: Do not Put New Apps to the Always-Hidden Section by Default

### ISSUE THREAD

**Issue by kozemirov** [jordanbaird/Ice#428] opened 2024-11-07 09:38 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Now all newly launched menu bar applications appear in the Always-Hidden Section. Therefore, I have to check the Always-Hidden Section to see whether there is accidentally something new or not. It is annoying and develops ADHD habits.

It would be great to have a choice of where new apps should appear: in the Visible Section, Hidden Section, or Always-Hidden Section.

I attached my example in Screenshots

### Screenshots

![Screenshot 2024-11-07 at 13 34 47 jpg](https://github.com/user-attachments/assets/7d8e890e-7800-4147-b127-9dd3f032c75d)

**Comment by jordanbaird** [comment] 2024-11-09 01:49
Duplicate of #6

**Closed by jordanbaird** 2024-11-09 01:49 UTC
Labels: Feature
