### ISSUE TITLE
[Bug]: Ice Freezing After Built-in Upgrade

### ISSUE THREAD

**Issue by uprprc777** [jordanbaird/Ice#364] opened 2024-09-20 12:56 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

After upgrading Ice using the built-in upgrade feature, the app freezes. While its settings and permissions panels appear, everyting unresponsive, and there is no splitter in the menu bar. By the way, both Accessibility and Screen Recording permissions are granted.

Using macOS "Force quit application" or "Acticity Monitor" to quit (not neccessarily force quit) does not help. When Ice quits and launches again, exactly same problem and behaviors.

The only workaround I’ve found is rebooting the Mac, which temporarily resolves the issue. However, the problem reoccurs during next upgrade.

I’ve encountered this issue at least twice: during the upgrade from version 0.11.2 to 0.11.3, and possibly from 0.11.1 to 0.11.2.

### Steps to Reproduce

1. Upgrading Ice using the built-in upgrade feature.
2. Let it download and click "restart to install".
3. Ice restarts and with its setting and permission panles popped up, but unresponsive.

### Ice Version

0.11.3 and others...

### macOS Version

14.7

**Comment by jordanbaird** [comment] 2024-09-20 17:01
This sounds like a pretty major bug. I'll work on getting a fix for this out as soon as I can.

**Comment by christiangierschner** [comment] 2024-09-23 12:06
same here, at least almost...
it doesn't matter which version of ice
but also MacOS 14.7
i upgraded last week and had no prior problems...

**Comment by jordanbaird** [comment] 2024-09-23 13:13
@christiangierschner Are you saying you've tried previous versions of Ice that had worked previously on an older macOS version and now it's failing?

**Comment by christiangierschner** [comment] 2024-09-23 14:59
yes, 10.5 works, 11.0 too and from 11.1 the pref panel freezes

**Closed** 2024-09-23 19:06 UTC
Labels: Bug

**Comment by jordanbaird** [comment] 2024-09-23 19:08
I believe I fixed the issue, but I can't reproduce it on either of my machines, so let me know once the next update is out if the problem still happens.

**Comment by jordanbaird** [comment] 2024-09-26 04:34
I'm going to treat this as an edge case for now. If people continue to have the same problem, I'll reopen this.

**Comment by christiangierschner** [comment] 2024-10-07 12:08
same issue with updates from 0.11.7 upwards, 0.11.6 is working fine

**Comment by christiangierschner** [comment] 2024-10-07 14:11
for the future reader: remove everything from ice (profiles, settings, etc.) and reinstall works

**Comment by jordanbaird** [comment] 2024-10-07 15:33
Adding to this: for an easy way to remove everything while uninstalling at the same time, use AppCleaner or PearCleaner. Both are free.
