### ISSUE TITLE
[Bug]: <YouTube Full Screen doesn't cover menu bar>

### ISSUE THREAD

**Issue by TrveBlve** [jordanbaird/Ice#66] opened 2024-06-04 19:48 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hi,

First off, thanks for your hard work - loving ICE so far. I have noticed one bug though: when going into full screen mode on YT, the menu bar is still somewhat visible. I tinkered with all the settings, but nothing helped. Thanks in advance!
<img width="1706" alt="Screenshot 2024-06-04 at 9 38 17 PM" src="https://github.com/jordanbaird/Ice/assets/171736133/33950a29-cd4c-4442-b3fd-e23a59fd1432">

### Steps to Reproduce

1. Play any video on YouTube
2. Set video to full screen mode

### Ice Version

0.8.0

### macOS Version

14.5

### Screenshots

<img width="1710" alt="Screenshot 2024-06-04 at 9 47 50 PM" src="https://github.com/jordanbaird/Ice/assets/171736133/0f62346f-332c-4dab-b0b8-801153b4b1b8">

**Comment by jordanbaird** [comment] 2024-06-05 03:59
Do you happen to be using Firefox?

**Comment by TrveBlve** [comment] 2024-06-05 08:16
Safari is my main browser, but the problem also persists in Firefox.

**Comment by humantorch** [comment] 2024-06-05 12:20
Confirmed the issue is happening for me as well using Arc Browser 1.44.3 (50502), macOS 14.5, Ice 0.8.0.

**Comment by jordanbaird** [comment] 2024-06-05 22:35
This is a very strange bug. There have been multiple reports of this or something similar happening in fullscreen. Every time I fix it, it seems to show up elsewhere. What's also strange is that sometimes, I can't even reproduce this issue on my computer.

**Comment by cmarhoover** [comment] 2024-06-05 22:44
This bug also occurs on my MacBook Pro with all fullscreen apps (tested with Safari, Mail, Reeder, and VMware Fusion).

**Comment by TrveBlve** [comment] 2024-06-06 22:21
Unfortunately, 0.9.0 didn't fix it.

**Comment by jordanbaird** [comment] 2024-06-06 22:43
@TrveBlve Yeah, 0.9.0 had a bunch of other fixes that had been building up over a couple months, so I needed to get a release out. Hopefully this can be resolved in the next release.

**Comment by TrveBlve** [comment] 2024-06-06 22:46
@jordanbaird - no stress man, we all appreciate the work you're putting in.Hopefully the whole Bartender debacle give you a much deserved boost :)

Have a good weekend man.

**Comment by jordanbaird** [comment] 2024-06-11 11:12
Closing this, as there have been multiple related reports of similar issues. I have opened #140 to track them together.

**Closed by jordanbaird** 2024-06-11 11:12 UTC
Labels: bug
