### ISSUE TITLE
[Feature Request]: Hide Icons Right to Ice Temporarily to Make Room on Notch Screens

### ISSUE THREAD

**Issue by RianGray** [jordanbaird/Ice#125] opened 2024-06-08 06:19 UTC
### Description

The one of the feature I liked from Bartender was temporarily hiding icons right to the divider (always shown icons) itself, instead of only hiding icons left to it. My understanding is that this was one of the choices for notch screens when there isn't enough space to expand hidden icons. Users could choose either to have a secondary menu box or to make room in the original menu bar.

I've included two screenshots of it happening on as an example. Because of the notch in the middle, not all icons can be displayed fully. So when the option is enabled, the icons to right of the divider are hidden temporarily. 

### Screenshots

![hidden-state](https://github.com/jordanbaird/Ice/assets/22567097/82118fcf-8ab7-4d66-913b-73c6aa8f8b21)
![expanded](https://github.com/jordanbaird/Ice/assets/22567097/03665cf3-02ae-4f15-b200-67498bda3bc7)

**Comment by jordanbaird** [comment] 2024-06-08 11:25
Duplicate of #68

**Closed by jordanbaird** 2024-06-08 11:25 UTC
Labels: enhancement
