### ISSUE TITLE
[Bug]: 1Password menubar item shows hidden after reboot

### ISSUE THREAD

**Issue by requisite-obscurity** [jordanbaird/Ice#301] opened 2024-08-06 14:41 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The 1Password menu bar icon doesn't work after a reboot.  It comes back to the always hidden area and needs to be dragged back to the menu bar and will work fine until a reboot.

### Steps to Reproduce

1Password 8, latest version, try using the menu bar icon and making it visible.  Reboot.  It will be hidden and the setting in Ice will need to be updated again to show the icon.

### Ice Version

0.10.4

### macOS Version

14.6

**Comment by jordanbaird** [comment] 2024-08-07 08:43
This is a duplicate of about a dozen other issues. See #298 for why this isn't a bug.

**Closed by jordanbaird** 2024-08-07 08:43 UTC
Labels: Bug
