### ISSUE TITLE
[Bug]: Apps move from visible to always hide after restart

### ISSUE THREAD

**Issue by yDRvuiiGupz4** [jordanbaird/Ice#150] opened 2024-06-12 15:00 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I have two application icons that move from the visible section to the always hide section after every restart.   The two apps are Zoom Workplace and 1Password.   Other apps stay in the assigned sections.

Zoom 6.0.11 (35001)
1Password 8.10.34

### Steps to Reproduce

1. Move Zoom and/or 1Password to visible section
2. Restart
3. Icons appear in Always Hide

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by ermonas** [comment] 2024-06-12 23:11
Having the same bug with 1Password. Don’t really use Zoom so I can’t confirm there.

**Comment by jordanbaird** [comment] 2024-06-13 02:10
Duplicate of #6

**Closed by jordanbaird** 2024-06-13 02:10 UTC
Labels: bug
