### ISSUE TITLE
[Feature Request]: Default behavior of new items

### ISSUE THREAD

**Issue by zhhanging** [jordanbaird/Ice#147] opened 2024-06-12 05:51 UTC
### Description

In current version, new items will all go to the "always hidden" area. It's a bit annoying to drag the icon by hand every time I launch a new app. I can't find a way to adjust in the settings. It would be nice to be able to change the default area of new menubar items.

**Comment by jordanbaird** [comment] 2024-06-12 06:01
Duplicate of #6

**Closed by jordanbaird** 2024-06-12 06:01 UTC
Labels: enhancement
