### ISSUE TITLE
[Bug]: <Tuneful App automatically heads to "Always Hidden" on Music pause.>

### ISSUE THREAD

**Issue by snapesworstmemory** [jordanbaird/Ice#354] opened 2024-09-17 08:12 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Tuneful (https://github.com/martinfekete10/Tuneful) is a menu bar app that shows a "Now Playing" of Spotify/Apple Music. It was working perfectly on the previous version of Ice, but since updating, every time I pause my music, Ice seems to move Tuneful to "Always Hidden" and then I manually have to bring it back.

### Steps to Reproduce

1. Make sure Tuneful is running.
2. Open Spotify
3. Play a song on Spotify (Tuneful will run in menu bar)
4. Pause playback on Spotify

### Ice Version

0.11.1

### macOS Version

Sequoia

**Comment by jordanbaird** [comment] 2024-09-17 09:50
Ice doesn't currently do any automatic movement of items (that's coming with the profiles feature, but we're not there yet). I was going to say that it's probably an update that Tuneful released, but looking their repository, they haven't put out anything since June, so I'm going to guess that this is a Sequoia change. Either way, this is a duplicate of #344, so I'll close this.

**Closed by jordanbaird** 2024-09-17 09:50 UTC
Labels: Bug
