### ISSUE TITLE
[Bug]: The native Shazam icon can't be placed in Ice in MacOS Sequoia 15.1.1

### ISSUE THREAD

**Issue by camilleroc** [jordanbaird/Ice#459] opened 2024-12-09 09:11 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

The Shazam icon cannot be moved in the Ice Bar and it does not appear in the application with the screenshot but its movement moves the other icon correctly

### Steps to Reproduce

1 : go in seting
2 : open controle center
3 :  turn ON the switch "Shazam" in the Bar menu

### Ice Version

0.11.12

### macOS Version

15.1.1

### Screenshots

<img width="1181" alt="Capture d’écran 2024-12-09 à 10 06 48" src="https://github.com/user-attachments/assets/4729c6be-c55a-49e2-b911-d7ae8a58aa2d">

**Comment by jordanbaird** [comment] 2024-12-28 13:30
Shazam is a special item that macOS prohibits from being hidden. Right now, Ice just chooses not to display it. We could probably handle this better though. Maybe still display the item, but show an alert if someone tries to hide it.

**Comment by jordanbaird** [comment] 2024-12-28 13:38
Duplicate of #440

**Closed by jordanbaird** 2024-12-28 13:38 UTC
Labels: Bug
