### ISSUE TITLE
[Feature Request]: Item Groups to help compartmentalize icons

### ISSUE THREAD

**Issue by depleur** [jordanbaird/Ice#135] opened 2024-06-10 21:47 UTC
### Description

Item groups, as implemented in Bartender, would prove to be extremely useful to manage clutter on smaller screens, including screens with a notch. Hopefully something of this kind can be implemented at some point in the future?

**Comment by jordanbaird** [comment] 2024-06-10 23:58
Duplicate of #46

**Closed by jordanbaird** 2024-06-10 23:58 UTC
Labels: enhancement
