### ISSUE TITLE
[Feature Request]: Option to automatically add new menu bar items to "always hidden", "hidden", or "visible" section 

### ISSUE THREAD

**Issue by brandonyoung4d** [jordanbaird/Ice#197] opened 2024-07-02 15:28 UTC
### Check existing feature requests

- [X] I have checked existing issues and believe that my feature request is not a duplicate

### Description

It would be nice to have an option to have new menu bar items automatically added to certain sections of the menu bar.

**Comment by jordanbaird** [comment] 2024-07-03 00:12
Duplicate of #6

**Closed by jordanbaird** 2024-07-03 00:12 UTC
Labels: enhancement
