### ISSUE TITLE
[Bug]: menu bar layout not recalling prior after restart

### ISSUE THREAD

**Issue by todddube** [jordanbaird/Ice#470] opened 2024-12-26 18:34 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When I've restarted my latptop since 0.11.x relases (I'm on 0.11.13) the menu bar layout is not recalling what is was prior. For example on restart it shows some in ice bar and some in menu bar.  I also have to re-arrange them. 

### Steps to Reproduce

1. restart
2. click as normal to show ice bar
3. see icons re-arranged or not in prior order.

### Ice Version

0.11.12

### macOS Version

15.3

**Comment by jordanbaird** [comment] 2024-12-28 13:10
Duplicate of #344

**Closed by jordanbaird** 2024-12-28 13:10 UTC
Labels: Bug
