### ISSUE TITLE
Items Hidden on Restart

### ISSUE THREAD

**Issue by bobbd2000** [jordanbaird/Ice#231] opened 2024-07-10 19:14 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

May be a duplicate but still an issue after the latest release. Even with the Always Hidden section turned off, a couple of menu bar items are moved after a restart. Specifically, 1Password is moved from visible to the far left end of Hidden, and Dropbox is moved from the middle of inside Hidden to the far left. These are the same two that got moved to the Always Hidden section. 

### Steps to Reproduce

1. Set up the Hidden and Visible sections.
2. Restart macOS
3. Observe whether any items are moved from visible to hidden.

### Ice Version

0.10.0

### macOS Version

14.5

**Comment by jordanbaird** [comment] 2024-07-10 19:52
This release was never going to fix the items being moved. Not sure if you've read through the comments of the other issues, but this happens because macOS is treating these items as newly created items and placing them at the far left of the menu bar. It isn't caused by Ice, and in fact will happen even if Ice isn't installed.

I do plan do address this behavior with #6 and #26, but this is not a bug. Closing as this is already tracked.

**Closed by jordanbaird** 2024-07-10 19:52 UTC
Labels: bug

**Comment by bobbd2000** [comment] 2024-07-10 19:56
Thanks for the fast reply. Bartender must be doing something special then. I will look for the changes from #6 and #23.

Thanks

Bob

**Comment by vincentbls** [comment] 2024-07-12 18:53
This is the case with 1Password and it's painful...
