### ISSUE TITLE
[Bug]: Visual glitch in split menubar on external display

### ISSUE THREAD

**Issue by jaimefordham** [jordanbaird/Ice#102] opened 2024-06-06 15:28 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

I'm running the "Split" menubar shape and on the external screen there seem to be display glitches as I move a window close to the menubar on the external screen.

<img width="1908" alt="Screenshot 2024-06-06 at 16 25 31" src="https://github.com/jordanbaird/Ice/assets/388731/c2beafbc-e8ce-43e8-a128-bd3b096b3002">

I'm running an M2 Macbook Air with the **notch**.

### Steps to Reproduce

1. Activate "split" menubar shape kind in Settings -> Menubar Appearance
2. Drag window from main display to external display
3. Drag window on external display to edge of menubar on external display

### Ice Version

0.9

### macOS Version

14.5

**Comment by jaimefordham** [comment] 2024-06-06 15:30
Better screenshot of the issue:

<img width="1917" alt="Screenshot 2024-06-06 at 16 29 48" src="https://github.com/jordanbaird/Ice/assets/388731/359b467c-b19c-4816-91b8-35a0ace5eb11">

**Comment by jordanbaird** [comment] 2024-06-06 17:01
Duplicate of #97

**Closed by jordanbaird** 2024-06-06 17:01 UTC
Labels: bug
