### ISSUE TITLE
[Bug]: Custom menu bar shape is redrawn when switching between Spaces

### ISSUE THREAD

**Issue by don-alfons** [jordanbaird/Ice#136] opened 2024-06-11 08:37 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

When switching from one Space to another (e.g. by swiping left or right with three fingers on the Trackpad), the menu bar appearance will lag. The menu bar is first drawn in the default macOS style/shape, a second later the Ice setting will be applied. This is especially apparent when using the "Split" menu bar shape in Ice (which is my favorite)
The same issue existed in Bartender for a while but they were somehow able to fix it. 

Thanks a lot for making Ice, this app is a lifesaver now!

### Steps to Reproduce

1. In Ice, change Menu Bar Shape to "Full" or "Split"
2. Open a new Space if you don't have one yet
3. Switch back and forth between Spaces and look at the menu bar

### Ice Version

0.9.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment] 2024-06-28 09:03
Duplicate of #58

**Closed by jordanbaird** 2024-06-28 09:03 UTC
Labels: bug

**Comment by jordanbaird** [comment] 2024-06-28 09:04
This will be implemented at some point, hopefully soon. I have a working mockup that I just need to transfer into the app.
