### ISSUE TITLE
[Bug]: Click to reveal hidden items causing the hidden apps to go underneath the app menu bar items

### ISSUE THREAD

**Issue by validatedev** [jordanbaird/Ice#124] opened 2024-06-07 23:24 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

As you can see in the screen recording, when clicking the "click to reveal hidden items" button, the right menubar items go below the left menubar items (application menubar items), but not all the time. The feature is unreliable.

### Steps to Reproduce

1. Click constantly on "Click to reveal hidden items (Ice icon)" button.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

https://github.com/jordanbaird/Ice/assets/29679552/99de2b6f-10f7-4375-b40e-5f6326e80195

**Comment by jordanbaird** [comment] 2024-06-08 00:52
Duplicate of #60

**Closed by jordanbaird** 2024-06-08 00:52 UTC
Labels: bug
