### ISSUE TITLE
[Bug]: 1password app always be hidden automaticlly

### ISSUE THREAD

**Issue by nanozuki** [jordanbaird/Ice#441] opened 2024-11-19 06:01 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

<img width="341" alt="image" src="https://github.com/user-attachments/assets/20c6f0cc-67e1-4731-b430-c9bf08752691">
<img width="685" alt="image" src="https://github.com/user-attachments/assets/b392c14e-cb89-4e7c-ac62-5e61d29e33b9">

Every time I drag "1password" from the hidden section to the visible section, it moves to the hidden section automatically after several days.

### Steps to Reproduce

1. drag "1password" from the hidden section to the visible section
2. wait several days, or reboot several times

### Ice Version

0.11.12

### macOS Version

15.1 (24B83)

**Comment by jordanbaird** [comment] 2024-11-20 05:12
Duplicate of #344

**Closed by jordanbaird** 2024-11-20 05:12 UTC
Labels: Bug
