### ISSUE TITLE
[Bug]: Game Mode icon resets its location

### ISSUE THREAD

**Issue by dblinnikov** [jordanbaird/Ice#279] opened 2024-07-29 09:11 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

When the Game Mode starts the icon always resets to the Visible section. The app doesn't move it to the previously assigned (in my case - "Hidden") section.

### Steps to Reproduce

1. Trigger Game Mode to be activated (e.g. GeforceNow)
2. Move the icon Game Mode to the "Hidden" section in the Ice interface
3. Quit the app from point 1 (it's important in order for the Game Mode icon to disappear entirely (another condition - don't have any other app triggering this mode - again, it's important to have the icon entirely disappeared))
4. Trigger again Game Mode

### Ice Version

0.10.3

### macOS Version

14.5

**Comment by jordanbaird** [comment] 2024-07-29 09:15
As with your previous bug report, this will be resolved once #6 and #26 are implemented. Not a bug, but a missing feature. Closing as this is tracked in those two issues.

**Closed by jordanbaird** 2024-07-29 09:15 UTC
Labels: Bug
