### ISSUE TITLE
[Bug]: Badgeify icons are placed in always hidden section

### ISSUE THREAD

**Issue by jeimu3u** [jordanbaird/Ice#460] opened 2024-12-11 10:56 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

When using badgeify (https://badgeify.app) and you move the menu bar icons to the visible section of the menu bar, if you close and reopen the application, it will place the menubar icons back into the always hidden section resulting in having to manually move them back.

### Steps to Reproduce

1. Open Ice
2. Open Badgeify
3. Move badgeify menu icons to visible menu bar
4. quit app (in my case outlook)
5. open app
6. menubar icon is back in always hidden section

### Ice Version

0.11.12

### macOS Version

15.2 (24C98)

**Comment by jordanbaird** [comment] 2024-12-28 13:26
Duplicate of #344

**Closed by jordanbaird** 2024-12-28 13:26 UTC
Labels: Bug
