### ISSUE TITLE
[Bug Report] Gradient Borders showing up in Full Screen.

### ISSUE THREAD

**Issue by patelheet30** [jordanbaird/Ice#7] opened 2024-02-04 23:32 UTC
If you're using Menu bar Tint, it shows up in full screen.

![Discord at 2024-02-04 at 23 30 27@2x](https://github.com/jordanbaird/Ice/assets/75808215/d029f5be-b4e6-44c7-84d4-c11869e2597a)

Version: 0.4.2

**Comment by jordanbaird** [comment] 2024-02-04 23:46
Thanks for the report! I'll work on getting this fixed.

**Comment by jordanbaird** [comment] 2024-02-05 03:36
Are you by chance using a second monitor? I can't reproduce this on my MacBook with a single screen.

**Comment by jordanbaird** [comment] 2024-02-05 14:53
I believe I was able to address the issue. It should be fixed in the next release. Let me know if it isn't.

**Closed by jordanbaird** 2024-02-05 14:53 UTC
