### ISSUE TITLE
[Bug]: Multi monitor wrong bar width and position

### ISSUE THREAD

**Issue by FederaikLudikon** [jordanbaird/Ice#127] opened 2024-06-08 10:56 UTC
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

When using multiple monitors at different resolutions the menu bar seem to have one single width for all of them instead of being different on each one, i submit some snapshots:
<img width="1920" alt="Monitor02" src="https://github.com/jordanbaird/Ice/assets/72828638/0c28ea55-6e20-4e01-ace6-e39912562e13">
<img width="1728" alt="Monitor01" src="https://github.com/jordanbaird/Ice/assets/72828638/8e4e8edf-3a2b-465f-a7d5-9bc24a377e49">
<img width="883" alt="SCR-20240608-losd" src="https://github.com/jordanbaird/Ice/assets/72828638/d692bf1c-21dc-4643-af3a-2e78130bf325">

### Steps to Reproduce

1) Connect a secondary monitor via thunderbolt
2) Change settings as in snapshot

### Ice Version

0.9.0

### macOS Version

Sonoma 14.5

### Screenshots

<img width="883" alt="SCR-20240608-losd" src="https://github.com/jordanbaird/Ice/assets/72828638/fcaf2ea7-3952-4266-bfbf-995793a3bf6a">
<img width="1920" alt="Monitor02" src="https://github.com/jordanbaird/Ice/assets/72828638/ee5ab1da-3cd5-4b24-a98a-cb9d582473e5">
<img width="1728" alt="Monitor01" src="https://github.com/jordanbaird/Ice/assets/72828638/2f6f0cb0-e72f-4c51-924d-2619fc498ca0">

**Comment by jordanbaird** [comment] 2024-06-08 11:28
Duplicate of #97

**Closed by jordanbaird** 2024-06-08 11:28 UTC
Labels: bug
