### ISSUE TITLE
[Feature Request]: Allow to show hidden items under the menu bar instead

### ISSUE THREAD

**Issue by fedecalendino** [jordanbaird/Ice#120] opened 2024-06-07 14:45 UTC
### Description

For notched macs, being able to show the hidden items *under* the menu bar would a great improvement since most of them are hidden by the OS.

<img width="223" alt="image" src="https://github.com/jordanbaird/Ice/assets/7383708/5e764f83-0221-4a90-bb2a-8c9306cb4b1e">

Thank you for all the work,
loving the app so far!

Fede.

**Comment by timbarlotta** [comment] 2024-06-07 15:07
What about only showing the "hidden" icons (hide the shown and always hidden) when displaying hidden icons.  Same when showing "always hidden" (hide the "hidden" and "shown" icons).

That would allow for more use cases where the notch is not in the way.

**Comment by leonard84** [comment] 2024-06-07 15:30
Duplicate of #1

**Closed** 2024-06-07 20:07 UTC
Labels: enhancement
