### ISSUE TITLE
[Bug]: Ice Settings window does not show up [OS 18.1 beta 4-5]

### ISSUE THREAD

**Issue by colintclai** [jordanbaird/Ice#375] opened 2024-09-24 06:04 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

After upgrading to Mac OS 18.1 beta 4, the Ice Settings window does not show up when I choose it from the Ice menu bar. I need to manually quit Ice and then relaunch Ice to be able to access the settings.

### Steps to Reproduce

1. right click the Ice menu bar item, settings screen does not show up
2. quit Ice
3. relaunch Ice
4. now the Settings window is shown

### Ice Version

0.11.3

### macOS Version

18.1 beta 5

**Comment by alexistrn** [comment] 2024-09-24 11:09
Hello @colintclai. Take a look at the latest release (0.11.4). The bug seems to be solved (I had the same problem).

**Comment by alexistrn** [comment] 2024-09-24 11:21
Hello @colintclai . Take a look at the latest release (0.11.4). The bug seems to be solved (thank's to @jordanbaird). I had the same problem and created a Github issue for that few days ago. Furthermore, macOS is in 15.0 or 15.1, not 18.1 version. That's for iOS. I'm on 15.0 and that's worked for me.

**Comment by jordanbaird** [comment] 2024-09-24 16:02
As, @alexistrn said, this should be fixed in 0.11.4.

**Comment by jordanbaird** [comment] 2024-09-24 16:02
Duplicate of #371

**Closed by jordanbaird** 2024-09-24 16:02 UTC
Labels: Bug
