### ISSUE TITLE
[Bug]: Dropbox icon won't stay in menu bar

### ISSUE THREAD

**Issue by stagelevel** [jordanbaird/Ice#398] opened 2024-10-09 22:50 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I place it in the menu bar but every time I restart my Mac its not there, then I have to manually put it back in the menu bar again.

### Steps to Reproduce

No steps

### Ice Version

0.11.9

### macOS Version

Sonoma 14.6.1

**Comment by jordanbaird** [comment] 2024-10-09 23:39
It almost certainly is being moved into the always-hidden section.

**Comment by jordanbaird** [comment] 2024-10-09 23:39
Duplicate of #344

**Closed by jordanbaird** 2024-10-09 23:39 UTC
Labels: Bug
