### ISSUE TITLE
[Bug]: <bug title>Temporary Menubar items do not reappear in menu

### ISSUE THREAD

**Issue by dgreenberg19** [jordanbaird/Ice#437] opened 2024-11-14 14:26 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

This may be a particular incompatiblity with Doll (https://github.com/xiaogdgenuine/Doll) which shows badges in the menubar for things like unread mail and messages. If I have the icons for those apps in the menubar and then read the items so the badge is no longer displayed, the badge does not reappear after a new item is received. As a workaround, I can set Doll to show the icon in the menubar regardless of the badge count.

### Steps to Reproduce

1. Add Doll to Visible section
2. View unread messages, eg., Mail or Messages which results in badge not showing (0 messages)
3. Doll gets moved to Hidden section

### Ice Version

.11.12

### macOS Version

15.2

**Comment by jordanbaird** [comment] 2024-11-27 21:10
Duplicate of #344

**Closed by jordanbaird** 2024-11-27 21:10 UTC
Labels: Bug
