### ISSUE TITLE
[Bug]: 1password appears in always-hidden section

### ISSUE THREAD

**Issue by jherran** [jordanbaird/Ice#281] opened 2024-07-31 10:16 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

When I update the app to a new version, or when I update de mac system version, the 1password app icon was moved to always-hidden section by itself.

### Steps to Reproduce

1. Add 1password app to visible items
<img width="621" alt="Screenshot 2024-07-31 at 12 08 25" src="https://github.com/user-attachments/assets/011d950e-8106-4751-aaa3-3a3e6a73ce25">

2. Check for updates
3. Update Ice when available
4. 1password will appear in always-hidden section

### Ice Version

0.10.3, 0.10.2, 0.10.1

### macOS Version

14.6, 14.5

**Comment by jordanbaird** [comment] 2024-07-31 12:12
This is a duplicate of about a dozen of other issues. See the comments of #266 for why this isn't a bug.

**Closed by jordanbaird** 2024-07-31 12:12 UTC
Labels: Bug
