### ISSUE TITLE
[Feature Request]: Spacers!

### ISSUE THREAD

**Issue by proactivematter** [jordanbaird/Ice#439] opened 2024-11-16 00:38 UTC
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

I just downloaded Ice and super impressed with the feature set. As far as I can tell it is on par or beyond Barkeeper, except for one critical feature...

Individual spacers, which you can add and define the width. It makes it so much easier to read groups of menubar apps when you can use spacers for grouping, e.g. "Display Settings Apps" "Audio Settings Apps" "Cloud Apps".

Wondering if there are any plans to this sometime soon?

Thanks for the great work

**Comment by jordanbaird** [comment] 2024-11-20 05:12
Duplicate of #91

**Closed by jordanbaird** 2024-11-20 05:12 UTC
Labels: Feature
