### ISSUE TITLE
[Feature Request]: show icons when specific app is active/on focus

### ISSUE THREAD

**Issue by FezVrasta** [jordanbaird/Ice#155] opened 2024-06-14 12:05 UTC
### Description

It would be useful to, for example, show the Docker icon when I'm using VS Code or XCode. Or show the Unsplash icon only when I'm on my desktop (Finder?).

**Comment by jordanbaird** [comment] 2024-06-14 20:49
Duplicate of #62

**Closed by jordanbaird** 2024-06-14 20:49 UTC
Labels: enhancement
