### ISSUE TITLE
[Feature Request]: Auto-Hide "Non-Hidden" Section When Expanding "Hidden" Section

### ISSUE THREAD

**Issue by milindhvijay** [jordanbaird/Ice#156] opened 2024-06-14 12:19 UTC
### Description

I would like to request a feature (present in Bartender) where the "non-hidden" section is automatically hidden when expanding the "hidden" section. This would provide more room for the icons in the "hidden" section and streamline the user interface.

Current Behavior:

Currently, when you expand the "hidden" section, the "non-hidden" section remains visible. This can lead to a cluttered interface, especially when there are many icons in both sections.

Proposed Behavior:

When the user expands the "hidden" section, the "non-hidden" section should automatically hide to make room for the icons in the "hidden" section. This would allow for a cleaner and more organized user interface.

Please consider adding an option in the settings to enable or disable this feature, giving users the flexibility to choose their preferred behavior.

**Comment by daryll-swer** [comment] 2024-06-14 12:23
+1 for this behaviour, it's seamless working fine on Bartender, and IIRC, on Bartender it also “hid” the Date/Clock when expanding the “hidden” section **into** the “non-hidden” section for maximum screen real-estate.

**Comment by jordanbaird** [comment] 2024-06-14 20:48
Duplicate of #68

**Closed by jordanbaird** 2024-06-14 20:48 UTC
Labels: enhancement
