### ISSUE TITLE
[Bug]: Ice cannot display menu bar items for automatically hidden menu bars.

### ISSUE THREAD

**Issue by kappesante** [jordanbaird/Ice#238] opened 2024-07-11 18:38 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

having the menubar hidden by default, any menu item in the hidden section cannot be shown. items on the right, always visible, are behaving correctly. this means that the hidden items are not shown on click, scroll, or hover. only the recorded combination shows the hidden items.

this is happening only since today, after the 0.10.2 update

### Steps to Reproduce

1. hover, scroll, or click on the area.
2. nothing happens.

### Ice Version

0.10.2

### macOS Version

14.5

### Screenshots

<img width="478" alt="Screenshot 2024-07-11 alle 20 34 32" src="https://github.com/jordanbaird/Ice/assets/16004367/ef694922-b934-434b-a01b-97261d66cd3d">

**Comment by kappesante** [comment] 2024-07-11 18:39
addition: right click on the empty area of the menubar does not show the options.

**Comment by jordanbaird** [comment] 2024-07-11 19:16
Duplicate of #201

**Closed by jordanbaird** 2024-07-11 19:16 UTC
Labels: bug

**Comment by kappesante** [comment] 2024-07-14 12:40
the issue is not present in a fullscreen app: the bar is shown on hover, click, or scroll.
only on windowed apps you must only use the ice icon or the shortcut.

**Comment by rmharp** [comment] 2025-02-20 02:04
I am also having this issue.
