### ISSUE TITLE
[Bug]: 1Password Icon automatically moved to Always-Hidden after macOS reboot

### ISSUE THREAD

**Issue by dblinnikov** [jordanbaird/Ice#278] opened 2024-07-29 09:04 UTC
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Every time after a macOS reboot (and only reboot - just the app restart doesn't trigger the issue), the 1Password icon is moved to the Always-Hidden section in the app.

### Steps to Reproduce

1. Move to 1Password icon to the Visible part of the Ice interface
2. Unlock 1Password (optional step - tried both ways)
3. Reboot macOS

### Ice Version

0.10.3

### macOS Version

14.5

**Comment by jordanbaird** [comment] 2024-07-29 09:13
This is a duplicate of about a dozen of other issues. See the comments of #266 for why this isn't a bug.

**Closed by jordanbaird** 2024-07-29 09:13 UTC
Labels: Bug
