### ISSUE TITLE
[Feature Request]: Show bar icons below native menu bar

### ISSUE THREAD

**Issue by Gaz492** [jordanbaird/Ice#138] opened 2024-06-11 10:22 UTC
### Description

A similar option to bartender 5 to show the hidden menu bar icons in a new dropdown bar if you hover/click on the Ice icon.

### Screenshots

![bar5](https://www.macbartender.com/Bartender5/img/BartenderBar@2x.png)

**Comment by jordanbaird** [comment] 2024-06-11 11:15
Duplicate of #1

**Closed by jordanbaird** 2024-06-11 11:15 UTC
Labels: enhancement
